/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevRouteImport } from './routes/dev'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContextRouteImport } from './routes/context'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as DevIdRouteImport } from './routes/dev.$id'
import { Route as CrmIdRouteImport } from './routes/crm.$id'
import { Route as ApiPublicClaudeAgentRouteImport } from './routes/api/public/claude-agent'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TasksRoute,
} as any)
const DevIdRoute = DevIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DevRoute,
} as any)
const CrmIdRoute = CrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrmRoute,
} as any)
const ApiPublicClaudeAgentRoute = ApiPublicClaudeAgentRouteImport.update({
  id: '/api/public/claude-agent',
  path: '/api/public/claude-agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/context': typeof ContextRoute
  '/crm': typeof CrmRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/crm/$id': typeof CrmIdRoute
  '/dev/$id': typeof DevIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/api/public/claude-agent': typeof ApiPublicClaudeAgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/context': typeof ContextRoute
  '/crm': typeof CrmRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/crm/$id': typeof CrmIdRoute
  '/dev/$id': typeof DevIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/api/public/claude-agent': typeof ApiPublicClaudeAgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/context': typeof ContextRoute
  '/crm': typeof CrmRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/crm/$id': typeof CrmIdRoute
  '/dev/$id': typeof DevIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/api/public/claude-agent': typeof ApiPublicClaudeAgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/context'
    | '/crm'
    | '/dev'
    | '/login'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/crm/$id'
    | '/dev/$id'
    | '/tasks/$id'
    | '/api/public/claude-agent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/context'
    | '/crm'
    | '/dev'
    | '/login'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/crm/$id'
    | '/dev/$id'
    | '/tasks/$id'
    | '/api/public/claude-agent'
  id:
    | '__root__'
    | '/'
    | '/context'
    | '/crm'
    | '/dev'
    | '/login'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/crm/$id'
    | '/dev/$id'
    | '/tasks/$id'
    | '/api/public/claude-agent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContextRoute: typeof ContextRoute
  CrmRoute: typeof CrmRouteWithChildren
  DevRoute: typeof DevRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRouteWithChildren
  ApiPublicClaudeAgentRoute: typeof ApiPublicClaudeAgentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/dev/$id': {
      id: '/dev/$id'
      path: '/$id'
      fullPath: '/dev/$id'
      preLoaderRoute: typeof DevIdRouteImport
      parentRoute: typeof DevRoute
    }
    '/crm/$id': {
      id: '/crm/$id'
      path: '/$id'
      fullPath: '/crm/$id'
      preLoaderRoute: typeof CrmIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/api/public/claude-agent': {
      id: '/api/public/claude-agent'
      path: '/api/public/claude-agent'
      fullPath: '/api/public/claude-agent'
      preLoaderRoute: typeof ApiPublicClaudeAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CrmRouteChildren {
  CrmIdRoute: typeof CrmIdRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmIdRoute: CrmIdRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface DevRouteChildren {
  DevIdRoute: typeof DevIdRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevIdRoute: DevIdRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

interface TasksRouteChildren {
  TasksIdRoute: typeof TasksIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksIdRoute: TasksIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContextRoute: ContextRoute,
  CrmRoute: CrmRouteWithChildren,
  DevRoute: DevRouteWithChildren,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRouteWithChildren,
  ApiPublicClaudeAgentRoute: ApiPublicClaudeAgentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
